--- 
title: "Sosiaalitieteiden tilastollisten menetelmien R-harjoituskurssi, 2 op"
author: "Terhi Auvinen, Samuli Koponen, Lauri Kortelainen & Antti Kouvo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
link-citations: yes
github-repo: "rstudio/bookdown-demo"
---

# R-harjoituskurssi {-}

```{r echo = FALSE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(tidyverse)
library(kableExtra)

#dataset <- readRDS(paste0("./dataset"))
#df <- readRDS(paste0("./dataset2"))

luo_kurssiaikataulu <- function(bold_row = 1) {
  asiat <- c("Käsiteltävät asiat (viitteellinen asiasisältö, muutoksia voi tulla)",
    "RStudioon ja R-kieleen tutustuminen",
             "Aineiston kuvailu: frekvenssijakauma, tunnusluvut, kuviot, osa-aineiston poimiminen ja aineston ryhmittäinen tarkastelu",
             "Yksinkertaiset muuttujamuunnokset, kahden muuttujan välinen yhteisvaihtelu, ristiintaulukointi",
             "Korrelaatiot ja hajotakuvio, summamuuttujan tekeminen",
             "Keskiarvotestit: t-testi ja ANOVA",
             "Kertausta ja ohjausta ryhmätehtävään")
  taul1 <- tibble(c("Osa", 1:6), col2 = asiat)
  taul1 %>% kable(col.names = NULL) %>% 
    row_spec(1, bold = TRUE, color = "white", background="#077d9e") %>% 
    row_spec(seq(2,nrow(taul1),2), background="#ccd8df") %>% 
    row_spec(seq(3,nrow(taul1),2), background="#e7ecf0") %>% 
    row_spec(bold_row, bold=TRUE, font_size = 17) %>% 
    kableExtra::kable_styling()
}
```





```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'tidyverse', 'magrittr'
), 'packages.bib')
```
